### ISSUE TITLE
Homebrew monster statblock won't import

### ISSUE THREAD

**Issue by Airwrecker** [Aioros/5e-statblock-importer#10]
Hi there, I tried to import two of my homebrew monster statblocks and I get the default monster statblock (the ability scores copies over but with no movement, AC 10, CR 1 (instead of CR 1/8), and empty Features.

Edit: I thought it has to do with the Net weapon since the Kuo-toa (from the 5E Monster Manual) has the same issue of not properly importing until I removed the Net weapon from its statblock. I removed the Net from the Phanaton Warrior but it still won't import. However, if I remove all Actions (Bite, Dagger, and Net) it properly imports.

![image](https://github.com/user-attachments/assets/30535b90-f7f2-4c16-9dcb-bc04c4adcac3)

I've pasted the statblock below:

----------------------
[Phanaton Warrior]
Small Humanoid, Typically Chaotic Good

Armor Class 13 (Leather Armor)
Hit Points 10 (3d6)
Speed 25 ft., climb 25 ft., fly 40 ft. 

STR
8 (-1)
DEX
14 (+2)
CON
10 (+0)
INT
9 (-1)
WIS
12 (+1)
CHA
11 (+0)

Skills Stealth +4, Survival +3
Senses Darkvision 60 ft., Passive Perception 11
Languages Common, Elvish, Sylvan
Challenge 1/4 (50 XP)
Proficiency Bonus +2

Traits
Glide. When the phanaton warrior flies, it cannot ascend, and it must descend 5 feet for every 10 feet traveled horizontally.

Stealthy. The phanaton warrior has advantage on Stealth checks.

Actions
Bite. Melee Weapon Attack: +1 to hit, reach 5 ft., one target. Hit: 1 (1d4 - 1) piercing damage.

Dagger. Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 4 (1d4 + 2) piercing damage.

Net. Melee or Ranged Weapon Attack: +3 to hit, range 5/15 ft., one Medium or smaller creature. Hit: The target is [restrained](https://www.dndbeyond.com/sources/dnd/free-rules/rules-glossary#RestrainedCondition). A creature can use its action to make a DC 10 Strength check to free itself or another creature in a net, ending the effect on a success. Dealing 5 slashing damage to the net (AC 10) frees the target without harming it and destroys the net.

**Comment by Aioros** [comment]
Hey, sorry, coming back to these issues a little late. There are a couple of separate issues working together in this case: not supporting a negative modifier (1d4 - 1) (which actually surprised me, lol), and a bug with parsing damage without a dice formula, like "5 slashing damage". I'll have both fixed in the next release, but a couple of things to keep in mind for this block:

1. Bite will show up as 1d4 + 2, because, at this time, the importer chooses the best ability between STR and DEX. That sounds a little weird, but it works very well with almost every 5e monster around.
2. Net will show a damage roll of 5 slashing damage because, well, that's what that "dealing 5 slashing damage" looks like to the parser. Might need to be manually fixed.

**Comment by Aioros** [comment]
New release is out, let me know if updating to v1.92.4 works for you.

**Comment by Airwrecker** [comment]
@Aioros It works now! Thanks!
